server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://111.229.226.99:3306/snow?characterEncoding=utf8&useSSL=false
    username: root
    password: t9@9Z703dfcd2
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  liquibase:
        enabled: true
        change-log: "classpath:liquibase/change_log/index.xml"
        contexts: dev