server:
  port: 8883
spring:
  datasource:
    url: jdbc:mysql://47.111.160.211:3306/beat_todo?characterEncoding=utf8&useSSL=false
    username: imag
    password: Imag@123456
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:resources/mapper/*Mapper.xml
  typeAliasesPackage: com.study.thread.model