spring:
  application:
    name: config-server
  server:
      port: 8888
    cloud:
      config:
        server:
          git:
            uri: https://github.com/forezp/SpringcloudConfig/
            searchPaths: respo
        label: master
          username: your username
          password: your password
#  如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写，本例子是公开仓库，放心使用。